exclude: ^(src/sipm_studio/simulations)
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: "v4.4.0"
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-yaml
  - id: check-json
  - id: check-toml
  - id: check-docstring-first
  - id: debug-statements
  - id: end-of-file-fixer
  - id: forbid-new-submodules
  - id: mixed-line-ending
  - id: requirements-txt-fixer
  - id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
- repo: https://github.com/codespell-project/codespell
  rev: "v2.2.2"
  hooks:
  - id: codespell
