name: sipm_studio

on:
  push:
    branches:
      - main
      - refactor
  pull_request:
  merge_group:
  release:

jobs:
  build:

    name: Test sipm_studio with python
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Install package and then test with pytest
        run: |
          pip install pytest
          python -m pip install --upgrade .
          python -m pytest --import-mode=append tests/

  test-docs:
      name: Build documentation
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - uses: actions/setup-python@v2
          with:
            python-version: '3.10'
        - name: Setup build environment
          run: |
            sudo apt-get install -y pandoc
            python -m pip install --upgrade pip wheel setuptools
            sudo apt-get install python3-sphinx
            python -m pip install --upgrade .
        - name: Build docs for current ref
          run: |
            cd docs
            make clean
            make
